apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: config-api
spec:
    replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template:
        metadata:
            labels:
              app: config-api
              tier: configuration
        spec:
            containers:
            - name: config-api
              image: emtdevelopment/configuration-api:1.1.18-SNAPSHOT-RC
              readinessProbe:
                httpGet:
                  path: /config-api/health
                  port: 1111
                initialDelaySeconds: 120
                timeoutSeconds: 60
                periodSeconds: 15
              livenessProbe:
                httpGet:
                  path: /config-api/health
                  port: 1111
                initialDelaySeconds: 120
                timeoutSeconds: 60
                periodSeconds: 15
              env:
              - name: GIT_CONFIG_URL
                value: https://github.com/BabcockEMTDevelopment/qa-configuration-properties
              ports:
              - containerPort: 1111

---

apiVersion: v1
kind: Service
metadata:
    name: config-api-gateway
    labels:
        app: config-api
        tier: configuration
spec:
    type: LoadBalancer
    ports:
    - port: 1111
    selector:
        app: config-api
        tier: configuration



